USE college; 

CREATE TABLE student(
	student_id INT PRIMARY KEY,
	name VARCHAR(100),
	address VARCHAR(100)
	);

ALTER TABLE student
MODIFY COLUMN name VARCHAR(100) NOT NULL,
MODIFY COLUMN student_id INT AUTO_INCREMENT,
ALTER address SET DEFAULT 'KATHMANDU';

ALTER TABLE student
ALTER address SET DEFAULT 'POKHARA';

ALTER TABLE student
MODIFY COLUMN name VARCHAR(100),
MODIFY COLUMN student_id INT,
ALTER address DROP DEFAULT;

DESC student;